volumes:
    sqlite-data:

services:
    mongo:
        build: ./backend/mongo
        container_name: mongo

    backend:
        build: ./backend
        depends_on:
            - mongo
        environment:
            MONGO_URI: mongodb://mongo:27017
            DATABASE_PATH: /data/app.sqlite
        container_name: backend
        expose:
            - "5000"
        # mount volume for the sqlite database
        volumes:
            - sqlite-data:/data

    frontend:
        build: .
        ports:
            - "8080:80"
        depends_on:
            - backend
                        
    playwright:
        build: ./e2e
        depends_on:
            - frontend
            - backend
        # # without that, chromium treats frontend url as not-secure 
        network_mode: "service:frontend"
        environment:
            # need to pass port 80 as this is port used for in-cluster frontend
            BASE_URL: http://localhost:80
            DATABASE_PATH: /data/app.sqlite
        volumes:
            - sqlite-data:/data