make all:
	g++ main.cpp -g02 -o unit_tests

make run:
	g++ main.cpp -g02 -o unit_tests && ./unit_tests

make win:
	g++ main.cpp -g02 -o unit_tests.exe

make winrun:
	g++ main.cpp -g02 -o unit_tests.exe && unit_tests.exe