server {

	root /usr/share/nginx/html; # that is a location in Docker container where app should be copied
	index index.html;

	add_header Cross-Origin-Opener-Policy "same-origin" always;
	add_header Cross-Origin-Embedder-Policy "require-corp" always;

	location / {
		# that is a frontend location
		try_files $uri $uri/ /index.html; # does file exist? if not render index.html
	}

	location /api {
		# that is a backend location
		proxy_pass http://backend:5000;
		proxy_set_header Host $host; # propagates original host headers to backend
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # preserves original client ips
		proxy_set_header X-Forwarded-Proto $scheme; # tells if request was using http or https
	}
}
